
export const events = [
  { logo: '/assets/events/hacknobuzz.png', title: 'Hacknobuzz', desc: 'Hacknobuzz, a dynamic event where creativity, collaboration and innovation take center stage and budding innovators come together to brainstorm, create and motivate.', reg_url: '', details_url: '' },
  { logo: '/assets/events/leadershipsummit.png', title: 'Leadership Summit', desc: 'The Leadership Summit fosters insightful discussions led by distinguished leaders across industries, where experts engage in thought-provoking conversations, sharing diverse perspectives on industry trends, business challenges and emerging technologies.', reg_url: '', details_url: '' },
  { logo: '/assets/events/creatorscorner.png', title: 'Creators Corner', desc: 'Looking to stand out in the digital space? Step into Creators Corner, where creativity meets opportunity! Join a thriving community of aspiring and established creators, connect with like-minded individuals and learn from industry leaders who have mastered the art of digital success.', reg_url: '', details_url: '' },
  { logo: '/assets/events/startupshowcase.png', title: 'Startup Showcase', desc: 'Are you ready to take your startup aspirations to the next level? Startup Showcase, hosted by E-Cell VSSUT, Burla at E-Summit 2025, is your golden opportunity to bring your ideas to life and make a lasting impact in the entrepreneurial world.', reg_url: '', details_url: ''},
  { logo: '/assets/events/iplauction.png', title: 'IPL Auction', desc: 'Join us at E-Cell, VSSUT for the grand Student IPL Auction, a one-of-a-kind experience where you don the mantle of a franchise owner, strategizing, bidding and assembling a squad destined for glory.', reg_url: '', details_url: '' },
  { logo: '/assets/events/laughterlounge.png', title: 'Esports Arena', desc: 'They say competition fuels greatness—so why not put your skills to the test? It’s time to switch gears and embrace the thrill of virtual battles! Join us at the Esports Arena, hosted by E-Cell VSSUT, Burla at E-Summit 2025 where top gamers will go head-to-head in an electrifying showdown.', reg_url: '', details_url: '' },
  { logo: '/assets/events/laughterlounge.png', title: 'Laughter Lounge', desc: 'After a day of brainstorming, networking and diving deep into ideas, it’s time to switch gears and embrace the lighter side of life! Join us at the Laughter Lounge, hosted by E-Cell, VSSUT, where some of the finest comedians will take the stage to tickle your funny bone.', reg_url: '', details_url: '' },
]